In [2]:
import pandas as pd
import mysql.connector

db = mysql.connector.connect(
    host="localhost",
    user="root",
    password="Manisha@2005",
    database="Project3"
)

cur = db.cursor()

print("Connected Successfully")

Connected Successfully

In [3]:
query = """
SELECT *
FROM clean_dataset
"""

df = pd.read_sql(query, db)

df.head()

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\4118525005.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, db)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [4]:
df.shape

(1200, 14)

In [5]:
df.columns

Index(['OrderID', 'Date', 'CustomerID', 'Product', 'Quantity', 'UnitPrice',
       'ShippingAddress', 'PaymentMethod', 'OrderStatus', 'TrackingNumber',
       'ItemsInCart', 'CouponCode', 'ReferralSource', 'TotalPrice'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   object
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), object(10)
memory usage: 131.4+ KB

In [7]:
df.describe()

          Quantity    UnitPrice  ItemsInCart   TotalPrice
count  1200.000000  1200.000000  1200.000000  1200.000000
mean      2.945833   356.412750     5.485000  1053.968300
std       1.407557   197.177146     2.281983   819.856558
min       1.000000    11.390000     1.000000    11.390000
25%       2.000000   186.062500     4.000000   410.520000
50%       3.000000   364.210000     5.000000   823.615000
75%       4.000000   521.570000     7.000000  1578.475000
max       5.000000   699.930000    10.000000  3456.400000

# Show All Orders

In [9]:
query = """
SELECT *
FROM clean_dataset
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\699022811.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04 00:00:00,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23 00:00:00,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27 00:00:00,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15 00:00:00,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08 00:00:00,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20 00:00:00,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04 00:00:00,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,,Facebook,1325.06
1197,ORD201197,2023-07-13 00:00:00,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22 00:00:00,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11 00:00:00,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

# Show Only Delivered Orders

In [10]:
query = """
SELECT OrderID,
       CustomerID,
       Product,
       TotalPrice
FROM clean_dataset
WHERE OrderStatus = 'Delivered'
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\1870120432.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

       OrderID CustomerID  Product  TotalPrice
0    ORD200004     C81840  Printer     2504.04
1    ORD200015     C39416  Printer      473.96
2    ORD200021     C99023  Monitor     1371.80
3    ORD200024     C17470   Laptop      461.90
4    ORD200025     C42577  Monitor      399.98
..         ...        ...      ...         ...
226  ORD201166     C95568    Chair      973.41
227  ORD201168     C89559   Laptop      662.84
228  ORD201171     C39911    Phone     2073.60
229  ORD201187     C26340     Desk      369.20
230  ORD201197     C79674   Tablet      873.68

[231 rows x 4 columns]

# Find Orders Above ₹2000

In [14]:
query = """
SELECT OrderID,
       Product,
       TotalPrice
FROM clean_dataset
WHERE TotalPrice > 2000
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\2109681891.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

       OrderID  Product  TotalPrice
0    ORD200000  Monitor     2853.10
1    ORD200002   Tablet     2753.40
2    ORD200004  Printer     2504.04
3    ORD200009     Desk     2037.52
4    ORD200010   Tablet     3129.85
..         ...      ...         ...
175  ORD201155  Printer     2138.28
176  ORD201156   Laptop     2763.12
177  ORD201171    Phone     2073.60
178  ORD201179   Laptop     2592.75
179  ORD201199   Tablet     2242.32

[180 rows x 3 columns]

# Sort Orders by Highest Revenue

In [15]:
query = """
SELECT OrderID,
       Product,
       TotalPrice
FROM clean_dataset
ORDER BY TotalPrice DESC
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\1598686102.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

        OrderID  Product  TotalPrice
0     ORD200789   Tablet     3456.40
1     ORD201122  Monitor     3390.95
2     ORD200632   Laptop     3390.80
3     ORD200469    Chair     3384.90
4     ORD200328   Tablet     3370.20
...         ...      ...         ...
1195  ORD200336   Laptop       18.20
1196  ORD200542   Tablet       17.98
1197  ORD200240   Tablet       17.24
1198  ORD200863    Phone       14.06
1199  ORD201161    Phone       11.39

[1200 rows x 3 columns]

# Count Total Orders

In [16]:
query = """
SELECT COUNT(*) AS Total_Orders
FROM clean_dataset
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\2720268811.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

   Total_Orders
0          1200

# Total Revenue Generated

In [17]:
query = """
SELECT SUM(TotalPrice) AS Total_Revenue
FROM clean_dataset
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\3317543653.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

   Total_Revenue
0     1264761.96

# Average Order Value

In [18]:
query = """
SELECT AVG(TotalPrice) AS Average_Order_Value
FROM clean_dataset
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\2553422997.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

   Average_Order_Value
0            1053.9683

# Total Revenue by Product

In [19]:
query = """
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM clean_dataset
GROUP BY Product
ORDER BY Revenue DESC
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\2781642233.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

# Number of Orders by Payment Method

In [20]:
query = """
SELECT PaymentMethod,
       COUNT(*) AS Total_Orders
FROM clean_dataset
GROUP BY PaymentMethod
ORDER BY Total_Orders DESC
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\3656111627.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

  PaymentMethod  Total_Orders
0        Online           258
1          Cash           246
2   Credit Card           234
3    Debit Card           232
4     Gift Card           230

# Orders by Referral Source

In [21]:
query = """
SELECT ReferralSource,
       COUNT(*) AS Orders
FROM clean_dataset
GROUP BY ReferralSource
ORDER BY Orders DESC
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\659304020.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

  ReferralSource  Orders
0      Instagram     259
1          Email     250
2         Google     241
3       Facebook     228
4       Referral     222

# Average Revenue by Order Status

In [22]:
query = """
SELECT OrderStatus,
       AVG(TotalPrice) AS Avg_Revenue
FROM clean_dataset
GROUP BY OrderStatus
ORDER BY Avg_Revenue DESC
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\4056190031.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

  OrderStatus  Avg_Revenue
0   Cancelled  1105.584840
1     Pending  1081.553376
2   Delivered  1050.217835
3     Shipped  1047.487574
4    Returned   984.929960

# Top 5 Products by Quantity Sold

In [23]:
query = """
SELECT Product,
       SUM(Quantity) AS Total_Quantity
FROM clean_dataset
GROUP BY Product
ORDER BY Total_Quantity DESC
LIMIT 5
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\3086241595.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

   Product  Total_Quantity
0    Chair           562.0
1  Printer           542.0
2   Laptop           535.0
3     Desk           508.0
4   Tablet           497.0

# Products Generating Revenue Above Average

In [24]:
query = """
SELECT Product,
       SUM(TotalPrice) AS Revenue
FROM clean_dataset
GROUP BY Product
HAVING Revenue >
(
    SELECT AVG(TotalPrice)
    FROM clean_dataset
)
ORDER BY Revenue DESC
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\2146203739.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

   Product    Revenue
0    Chair  195620.11
1  Printer  195612.61
2   Laptop  192126.56
3   Tablet  186568.95
4  Monitor  175651.41
5     Desk  167459.93
6    Phone  151722.39

# Top 5 Customers by Spending

In [25]:
query = """
SELECT CustomerID,
       SUM(TotalPrice) AS Total_Spending
FROM clean_dataset
GROUP BY CustomerID
ORDER BY Total_Spending DESC
LIMIT 5
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\1307847626.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

  CustomerID  Total_Spending
0     C38840         5723.23
1     C57276         3456.40
2     C67260         3390.80
3     C13877         3384.90
4     C18404         3370.20

# Revenue by Payment Method

In [26]:
query = """
SELECT PaymentMethod,
       SUM(TotalPrice) AS Revenue
FROM clean_dataset
GROUP BY PaymentMethod
ORDER BY Revenue DESC
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\1450814566.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

  PaymentMethod    Revenue
0   Credit Card  263847.63
1        Online  262442.94
2          Cash  259786.29
3     Gift Card  246323.92
4    Debit Card  232361.18

# Order Status Distribution

In [27]:
query = """
SELECT OrderStatus,
       COUNT(*) AS Total_Orders
FROM clean_dataset
GROUP BY OrderStatus
ORDER BY Total_Orders DESC
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\2816331896.py:9: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

  OrderStatus  Total_Orders
0   Cancelled           250
1    Returned           247
2     Pending           237
3     Shipped           235
4   Delivered           231

# Orders Using Coupons

In [28]:
query = """
SELECT COUNT(*) AS Orders_With_Coupons
FROM clean_dataset
WHERE CouponCode IS NOT NULL
AND CouponCode <> ''
"""

pd.read_sql(query, db)

C:\Users\HP\AppData\Local\Temp\ipykernel_18896\3553969633.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql(query, db)

   Orders_With_Coupons
0                  891